name: flutter_ui_bloc
description: A new Flutter project.
version: 0.5.3
homepage: https://github.com/BreX900/flutter_ui_bloc
repository: https://github.com/BreX900/flutter_ui_bloc

# flutter pub publish --dry-run

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  mime: ^1.0.0
  pure_extensions: ^4.0.0
  flutter_extensions: ^4.0.0
  built_collection: ^5.1.0

  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  form_bloc: ^0.20.0
  flutter_form_bloc: ^0.20.0

#  provider: ^6.0.0

  cross_file: ^0.3.1+5

  dotted_border: ^2.0.0+1

  json_annotation: ^4.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
